# Generated by Django 3.1.4 on 2021-03-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210318_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='pred',
            name='start',
            field=models.CharField(default='2021-03-18', max_length=10),
        ),
    ]
