# Generated by Django 3.1.7 on 2021-04-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pred_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('end', models.CharField(default='2021-04-06', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='pred',
            name='start',
            field=models.CharField(default='2021-04-06', max_length=10),
        ),
    ]
