# Generated by Django 3.1.4 on 2021-04-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210406_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='end',
            field=models.CharField(default='2021-04-07', max_length=10),
        ),
        migrations.AlterField(
            model_name='pred',
            name='start',
            field=models.CharField(default='2021-04-07', max_length=10),
        ),
    ]
