# Generated by Django 3.1.4 on 2021-04-08 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210407_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='day2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('cases', models.IntegerField()),
                ('pred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.data')),
            ],
        ),
    ]
