# Generated by Django 3.1.4 on 2021-04-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210410_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day2',
            old_name='pred',
            new_name='data',
        ),
    ]
